### ISSUE TITLE
Can sdists be published after wheels?

### ISSUE THREAD

**Issue by godlygeek** [mrabarnett/mrab-regex#440]
As things are today, sdists for new versions are published about 20 minutes before wheels for those new versions. That means that there's a 20 minute window while you're publishing where a `pip install regex` (or, more likely, some package like `black` that depends on `regex`) will find the sdist for a new version but no wheel for it, and so it will try to build the sdist from source (possibly failing if the build dependencies aren't available), unless someone has deliberately pinned to an old version of `regex` or used `--prefer-binary`.

If the order could be changed so that the sdist is only published after all the wheels, that would remove this failure mode by ensuring that `pip` always sees a wheel for a version as long as one was built for the platform you're installing on.

I think getting this in the desired order for the `build_in_manylinux2010` stage only requires that the "Upload source distribution" and "Upload manylinux1_x86_64 wheels" steps be swapped, which would actually be good enough for my use case since the CI this is causing me trouble on is x86_64, though it would be nicer if sdists were published after all architectures' wheels if possible.

**Comment by mrabarnett** [comment]
I've identified the problem. It shouldn't happen again.

**Comment by godlygeek** [comment]
You're awesome!

**Comment by ghost** [comment]
> the build_in_manylinux2010 stage only requires that the "Upload source distribution" and "Upload manylinux1_x86_64 wheels" steps be swapped,

This is only upload to an intermediate workspace, not to PyPI.

> Upload-Artifact v2
> This uploads artifacts from your workflow allowing you to share data between jobs and store data once a workflow is complete.

Uploading to PyPI is done by the last job. Splitting it to two steps may solve this problem.
```yaml
  # Upload to PyPI
  upload_pypi:
    name: Publish to PyPI
    needs: [build_wheels, build_in_manylinux2010, build_arch_wheels]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: regex-files
          path: dist

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          skip_existing: true
          verbose: true
```
